version: '3.9'

services:
  micro-appoint-users:
    depends_on:
      - mongodb
    build: .
    hostname: users
    env_file:
      - .env
    image: micro-appoint-users
    container_name: users-backend
    networks:
      - micro-appoint-net
    ports:
      - 50053:50051
        #volumes:
        #  - .:/app

  mongodb:
    image: mongo
    container_name: users-db
    hostname: users-db
    restart: always
    networks:
      - micro-appoint-net
    ports:
      - 27019:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
      - MONGO_INITDB_ROOT_DATABASE=${DB_NAME}
    volumes:
      - db-data:/data/db
      - db-config:/data/configdb

  mongo-express:
    image: mongo-express
    restart: always
    networks:
      - micro-appoint-net
    ports:
      - 8083:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: users-db
      ME_CONFIG_MONGODB_PORT: "27017"

volumes:
  db-data:
    driver: local
  db-config:
    driver: local

networks:
  micro-appoint-net:
    name: micro-appoint-net
    external: true
