version: '3.9'

services:
  micro-appoint-users:
    depends_on:
      - mongodb
    build: .
    env_file:
      - .env
    image: micro-appoint-users
    container_name: users-backend
    networks:
      - users-net
    ports:
      - 8080:8080
    volumes:
      - .:/app

  mongodb:
    image: mongo
    container_name: users-db
    restart: always
    networks:
      - users-net
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
      - MONGO_INITDB_ROOT_DATABASE=${DB_NAME}
    volumes:
      - db-data:/data/db
      - db-config:/data/configdb

volumes:
  db-data:
    driver: local
  db-config:
    driver: local


networks:
  users-net:
    driver: bridge
