apiVersion: v1
kind: Service
metadata:
  name: micro-appoint-users-backend-service
spec:
  selector:
    app: micro-appoint-users-backend
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051
---
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: micro-appoint-users-backend-deployment
  labels:
    app: micro-appoint-users-backend
spec:
  selector:
    matchLabels:
      app: micro-appoint-users-backend 
  replicas: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: micro-appoint-users-backend
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: micro-appoint-users-backend
        image: msik/micro-appoint-users:latest
        env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: micro-appoint-users-mongo-secret
              key: db-user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: micro-appoint-users-mongo-secret
              key: db-password
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: micro-appoint-users-mongo-config
              key: db-name
        - name: DB_HOSTNAME
          valueFrom:
            configMapKeyRef:
              name: micro-appoint-users-mongo-config
              key: db-hostname
        ports:
        - containerPort: 50051
